platform :osx, "10.6"

pod 'PryvApiKit', :path => '../../sdk-objectivec-apple/PryvApiKit.podspec'

pod 'SSKeychain', '~> 1.1.0'

#target 'PrYv-OSX-ExampleTests', :exclusive => true do
#pod 'OCMock'
#end
