platform :osx, "10.7"

xcodeproj 'Pryv.xcodeproj'

pod 'PryvApiKit', :path => '../../sdk-objectivec-apple/PryvApiKit.podspec'
pod 'SSKeychain', '~> 1.1.0'
pod 'StartAtLoginController', '~> 0.0'
#pod 'AXStatusItemPopup', '~> 0.0'

#target 'PrYv-OSX-ExampleTests', :exclusive => true do
#pod 'OCMock'
#end
